name: buildjupyterbook
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - matplotlib
  - numpy
  - scipy
  - h5py
  - cartopy
  - pip
  - pip:
      - pymap3d
      - apexpy
      - madrigalWeb
